version: 0.0
os: linux
files:
  - source: /client
    destination: /var/app/current/client
  - source: /config
    destination: /var/app/current/config
  - source: /gulp
    destination: /var/app/current/gulp
  - source: /scripts
    destination: /var/app/current/scripts
  - source: /server
    destination: /var/app/current/server
  - source: /test
    destination: /var/app/current/test
  - source: first-time-setup.js
    destination: /var/app/current/first-time-setup.js
  - source: server.js
    destination: /var/app/current/server.js
  - source: package.json
    destination: /var/app/current/package.json
  - source: package-lock.json
    destination: /var/app/current/package-lock.json
  - source: node-app
    destination: /var/app/current/node-app

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup_environment
      timeout: 300
      runas: root