version: 0.0
os: linux
files:
  - source: /client
    destination: /jet/app/current/client
  - source: /config
    destination: /jet/app/current/config
  - source: /gulp
    destination: /jet/app/current/gulp
  - source: /scripts
    destination: /jet/app/current/scripts
  - source: /server
    destination: /jet/app/current/server
  - source: /test
    destination: /jet/app/current/test
  - source: first-time-setup.js
    destination: /jet/app/current/
  - source: server.js
    destination: /jet/app/current/
  - source: package.json
    destination: /jet/app/current/
  - source: package-lock.json
    destination: /jet/app/current/
  - source: node-app
    destination: /jet/app/current/
  - source: gulpfile.js
    destination: /jet/app/current/
  - source: .babelrc
    destination: /jet/app/current/
  - source: .editorconfig
    destination: /jet/app/current/
  - source: .eslintignore
    destination: /jet/app/current/
  - source: .eslintrc.json
    destination: /jet/app/current/
  - source: .travis.yml
    destination: /jet/app/current/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup_environment
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: root